add_test( SumColumn.Basic /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=SumColumn.Basic]==] --gtest_also_run_disabled_tests)
set_tests_properties( SumColumn.Basic PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( SumColumn.Write /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=SumColumn.Write]==] --gtest_also_run_disabled_tests)
set_tests_properties( SumColumn.Write PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( SumColumn.Read /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=SumColumn.Read]==] --gtest_also_run_disabled_tests)
set_tests_properties( SumColumn.Read PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( SumColumn.Merge /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=SumColumn.Merge]==] --gtest_also_run_disabled_tests)
set_tests_properties( SumColumn.Merge PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( SumColumn.Extract /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=SumColumn.Extract]==] --gtest_also_run_disabled_tests)
set_tests_properties( SumColumn.Extract PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( SumColumn.ToBytes /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=SumColumn.ToBytes]==] --gtest_also_run_disabled_tests)
set_tests_properties( SumColumn.ToBytes PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( SumColumn.FromBytes /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=SumColumn.FromBytes]==] --gtest_also_run_disabled_tests)
set_tests_properties( SumColumn.FromBytes PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( SumColumn.ScaleBuckets /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=SumColumn.ScaleBuckets]==] --gtest_also_run_disabled_tests)
set_tests_properties( SumColumn.ScaleBuckets PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( CountColumn.Basic /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=CountColumn.Basic]==] --gtest_also_run_disabled_tests)
set_tests_properties( CountColumn.Basic PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( CountColumn.Write /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=CountColumn.Write]==] --gtest_also_run_disabled_tests)
set_tests_properties( CountColumn.Write PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( CountColumn.Read /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=CountColumn.Read]==] --gtest_also_run_disabled_tests)
set_tests_properties( CountColumn.Read PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( CountColumn.Merge /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=CountColumn.Merge]==] --gtest_also_run_disabled_tests)
set_tests_properties( CountColumn.Merge PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( CountColumn.Extract /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=CountColumn.Extract]==] --gtest_also_run_disabled_tests)
set_tests_properties( CountColumn.Extract PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( CountColumn.ToBytes /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=CountColumn.ToBytes]==] --gtest_also_run_disabled_tests)
set_tests_properties( CountColumn.ToBytes PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( CountColumn.FromBytes /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=CountColumn.FromBytes]==] --gtest_also_run_disabled_tests)
set_tests_properties( CountColumn.FromBytes PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( CountColumn.ScaleBuckets /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=CountColumn.ScaleBuckets]==] --gtest_also_run_disabled_tests)
set_tests_properties( CountColumn.ScaleBuckets PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( MinColumn.Basic /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=MinColumn.Basic]==] --gtest_also_run_disabled_tests)
set_tests_properties( MinColumn.Basic PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( MinColumn.Write /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=MinColumn.Write]==] --gtest_also_run_disabled_tests)
set_tests_properties( MinColumn.Write PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( MinColumn.Read /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=MinColumn.Read]==] --gtest_also_run_disabled_tests)
set_tests_properties( MinColumn.Read PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( MinColumn.Merge /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=MinColumn.Merge]==] --gtest_also_run_disabled_tests)
set_tests_properties( MinColumn.Merge PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( MinColumn.Extract /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=MinColumn.Extract]==] --gtest_also_run_disabled_tests)
set_tests_properties( MinColumn.Extract PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( MinColumn.ToBytes /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=MinColumn.ToBytes]==] --gtest_also_run_disabled_tests)
set_tests_properties( MinColumn.ToBytes PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( MinColumn.FromBytes /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=MinColumn.FromBytes]==] --gtest_also_run_disabled_tests)
set_tests_properties( MinColumn.FromBytes PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( MinColumn.ScaleBuckets /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=MinColumn.ScaleBuckets]==] --gtest_also_run_disabled_tests)
set_tests_properties( MinColumn.ScaleBuckets PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( MaxColumn.Basic /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=MaxColumn.Basic]==] --gtest_also_run_disabled_tests)
set_tests_properties( MaxColumn.Basic PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( MaxColumn.Write /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=MaxColumn.Write]==] --gtest_also_run_disabled_tests)
set_tests_properties( MaxColumn.Write PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( MaxColumn.Read /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=MaxColumn.Read]==] --gtest_also_run_disabled_tests)
set_tests_properties( MaxColumn.Read PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( MaxColumn.Merge /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=MaxColumn.Merge]==] --gtest_also_run_disabled_tests)
set_tests_properties( MaxColumn.Merge PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( MaxColumn.Extract /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=MaxColumn.Extract]==] --gtest_also_run_disabled_tests)
set_tests_properties( MaxColumn.Extract PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( MaxColumn.ToBytes /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=MaxColumn.ToBytes]==] --gtest_also_run_disabled_tests)
set_tests_properties( MaxColumn.ToBytes PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( MaxColumn.FromBytes /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=MaxColumn.FromBytes]==] --gtest_also_run_disabled_tests)
set_tests_properties( MaxColumn.FromBytes PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( MaxColumn.ScaleBuckets /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=MaxColumn.ScaleBuckets]==] --gtest_also_run_disabled_tests)
set_tests_properties( MaxColumn.ScaleBuckets PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( LastColumn.Basic /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=LastColumn.Basic]==] --gtest_also_run_disabled_tests)
set_tests_properties( LastColumn.Basic PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( LastColumn.Write /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=LastColumn.Write]==] --gtest_also_run_disabled_tests)
set_tests_properties( LastColumn.Write PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( LastColumn.Read /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=LastColumn.Read]==] --gtest_also_run_disabled_tests)
set_tests_properties( LastColumn.Read PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( LastColumn.Merge /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=LastColumn.Merge]==] --gtest_also_run_disabled_tests)
set_tests_properties( LastColumn.Merge PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( LastColumn.Extract /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=LastColumn.Extract]==] --gtest_also_run_disabled_tests)
set_tests_properties( LastColumn.Extract PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( LastColumn.ToBytes /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=LastColumn.ToBytes]==] --gtest_also_run_disabled_tests)
set_tests_properties( LastColumn.ToBytes PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( LastColumn.FromBytes /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=LastColumn.FromBytes]==] --gtest_also_run_disabled_tests)
set_tests_properties( LastColumn.FromBytes PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( LastColumn.ScaleBuckets /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=LastColumn.ScaleBuckets]==] --gtest_also_run_disabled_tests)
set_tests_properties( LastColumn.ScaleBuckets PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( RawTimestamps.Basic /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=RawTimestamps.Basic]==] --gtest_also_run_disabled_tests)
set_tests_properties( RawTimestamps.Basic PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( RawTimestamps.Write /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=RawTimestamps.Write]==] --gtest_also_run_disabled_tests)
set_tests_properties( RawTimestamps.Write PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( RawTimestamps.Merge /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=RawTimestamps.Merge]==] --gtest_also_run_disabled_tests)
set_tests_properties( RawTimestamps.Merge PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( RawTimestamps.Extract /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=RawTimestamps.Extract]==] --gtest_also_run_disabled_tests)
set_tests_properties( RawTimestamps.Extract PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( RawTimestamps.ToBytes /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=RawTimestamps.ToBytes]==] --gtest_also_run_disabled_tests)
set_tests_properties( RawTimestamps.ToBytes PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( RawTimestamps.FromBytes /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=RawTimestamps.FromBytes]==] --gtest_also_run_disabled_tests)
set_tests_properties( RawTimestamps.FromBytes PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( RawTimestamps.GetTimeRange /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=RawTimestamps.GetTimeRange]==] --gtest_also_run_disabled_tests)
set_tests_properties( RawTimestamps.GetTimeRange PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( RawValues.Basic /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=RawValues.Basic]==] --gtest_also_run_disabled_tests)
set_tests_properties( RawValues.Basic PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( RawValues.Write /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=RawValues.Write]==] --gtest_also_run_disabled_tests)
set_tests_properties( RawValues.Write PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( RawValues.Merge /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=RawValues.Merge]==] --gtest_also_run_disabled_tests)
set_tests_properties( RawValues.Merge PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( RawValues.Extract /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=RawValues.Extract]==] --gtest_also_run_disabled_tests)
set_tests_properties( RawValues.Extract PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( RawValues.ToBytes /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=RawValues.ToBytes]==] --gtest_also_run_disabled_tests)
set_tests_properties( RawValues.ToBytes PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( RawValues.FromBytes /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=RawValues.FromBytes]==] --gtest_also_run_disabled_tests)
set_tests_properties( RawValues.FromBytes PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ReadRawColumn.Basic /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=ReadRawColumn.Basic]==] --gtest_also_run_disabled_tests)
set_tests_properties( ReadRawColumn.Basic PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ReadRawColumn.Write /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=ReadRawColumn.Write]==] --gtest_also_run_disabled_tests)
set_tests_properties( ReadRawColumn.Write PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ReadRawColumn.Read /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=ReadRawColumn.Read]==] --gtest_also_run_disabled_tests)
set_tests_properties( ReadRawColumn.Read PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ReadRawColumn.Merge /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=ReadRawColumn.Merge]==] --gtest_also_run_disabled_tests)
set_tests_properties( ReadRawColumn.Merge PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ReadRawColumn.Extract /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=ReadRawColumn.Extract]==] --gtest_also_run_disabled_tests)
set_tests_properties( ReadRawColumn.Extract PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( AvgColumn.Basic /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=AvgColumn.Basic]==] --gtest_also_run_disabled_tests)
set_tests_properties( AvgColumn.Basic PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( AvgColumn.Read /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=AvgColumn.Read]==] --gtest_also_run_disabled_tests)
set_tests_properties( AvgColumn.Read PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( Level.ReadWrite /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=Level.ReadWrite]==] --gtest_also_run_disabled_tests)
set_tests_properties( Level.ReadWrite PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( Memtable.ReadWrite /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=Memtable.ReadWrite]==] --gtest_also_run_disabled_tests)
set_tests_properties( Memtable.ReadWrite PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( Memtable.ExtractColumns /home/pavel/Documents/code/project/timekv/src/make/tskv-test [==[--gtest_filter=Memtable.ExtractColumns]==] --gtest_also_run_disabled_tests)
set_tests_properties( Memtable.ExtractColumns PROPERTIES WORKING_DIRECTORY /home/pavel/Documents/code/project/timekv/src/make SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set( tskv-test_TESTS SumColumn.Basic SumColumn.Write SumColumn.Read SumColumn.Merge SumColumn.Extract SumColumn.ToBytes SumColumn.FromBytes SumColumn.ScaleBuckets CountColumn.Basic CountColumn.Write CountColumn.Read CountColumn.Merge CountColumn.Extract CountColumn.ToBytes CountColumn.FromBytes CountColumn.ScaleBuckets MinColumn.Basic MinColumn.Write MinColumn.Read MinColumn.Merge MinColumn.Extract MinColumn.ToBytes MinColumn.FromBytes MinColumn.ScaleBuckets MaxColumn.Basic MaxColumn.Write MaxColumn.Read MaxColumn.Merge MaxColumn.Extract MaxColumn.ToBytes MaxColumn.FromBytes MaxColumn.ScaleBuckets LastColumn.Basic LastColumn.Write LastColumn.Read LastColumn.Merge LastColumn.Extract LastColumn.ToBytes LastColumn.FromBytes LastColumn.ScaleBuckets RawTimestamps.Basic RawTimestamps.Write RawTimestamps.Merge RawTimestamps.Extract RawTimestamps.ToBytes RawTimestamps.FromBytes RawTimestamps.GetTimeRange RawValues.Basic RawValues.Write RawValues.Merge RawValues.Extract RawValues.ToBytes RawValues.FromBytes ReadRawColumn.Basic ReadRawColumn.Write ReadRawColumn.Read ReadRawColumn.Merge ReadRawColumn.Extract AvgColumn.Basic AvgColumn.Read Level.ReadWrite Memtable.ReadWrite Memtable.ExtractColumns)
